global:
  listen_address:   ":8083"
  cert_file:        ""
  cert_key:         ""

backends:

  - backend:        "etcd"
    id:             "etcd"
    nodes:          ["http://127.0.0.1:2379"]
    username:       ""
    password:       ""

  - backend:        "consul"
    id:             "consul"
    nodes:          ["http://127.0.0.1:8500"]
    username:       ""
    password:       ""