[global]


[[templates]]
urls = ["http://127.0.0.1:8080","http://127.0.0.1:8081"]
path = "/{{ replaceAll \".ospd.net\" \"\" hostname }}/test.json"
src = "config/inputs.tmpl"
temp = "/tmp/.localhost.conf"
dest = "/tmp/localhost.conf"
