[global]


[[templates]]
urls = ["http://127.0.0.1:8083"]
path = "/api/v2/etcd/{{ replaceAll \".ospd.net\" \"\" hostname }}/apps"
create = true
src = "config/inputs.tmpl"
temp = "/tmp/.localhost.conf"
dest = "/tmp/localhost.conf"
