[global]

[[templates]]
urls = ["http://127.0.0.1:8083"]
path = "/api/v2/etcd/ps/hosts/test03/test-host149?recursive=true"
#urls = ["http://localhost:2379/v2/keys"]
create = true
src = "config/inputs.tmpl"
src_match = "config/inputs*.tmpl"
#temp = "/tmp/.localhost.conf"
dest = "/tmp/localhost.conf"
username = "test"
password = "GExtqw=="
