global:
  cert_file:        ""
  cert_key:         ""

backends:

  - backend:        "etcd"
    id:             "etcd"
    nodes:          ["http://127.0.0.1:2379"]
    write:
      username:       ""
      password:       ""
      keys:           [".*"]
    read:
      keys:           [".*"]

  - backend:        "consul"
    id:             "consul"
    nodes:          ["http://127.0.0.1:8500"]
    write:
      username:       ""
      password:       ""