[[template]]
urls = ["http://localhost:8080/localhost"]
src = "config/inputs.tmpl"
dest = "/tmp/inputs.conf"
reload_cmd = "kill -1 43235"

#[[template]]
#urls = ["http://localhost:8080/localhost1"]
#src = "config/netmap.tmpl"
#dest = "/tmp/netmap.conf"