[global]


[[templates]]
urls = ["http://{{ replaceAll \".ospd.net\" \"\" hostname }}:8080/test.json","http://{{ hostname }}:8080/test2.json"]
src = "config/inputs.tmpl"
temp = "/tmp/.localhost.conf"
dest = "/tmp/localhost.conf"
