name: Create and publish a Docker image

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest commit message
        id: get_commit_message
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check commit message against regex
        id: check_regex
        run: |
          if [[ "${{ env.COMMIT_MESSAGE }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "MATCH=true" >> $GITHUB_ENV
          else
            echo "MATCH=false" >> $GITHUB_ENV
          fi

      - name: Log in to the Container registry
        if: env.MATCH == 'true'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: env.MATCH == 'true'
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        if: env.MATCH == 'true'
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/ltkh/cdserver:${{ env.COMMIT_MESSAGE }}
          labels: ${{ steps.meta.outputs.labels }}